import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>
          PlanetScale Serverless Driver on Next.js + Netlify Edge Functions
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          PlanetScale Serverless Driver on Next.js + Netlify Edge Functions
        </h1>

        <p>
          <Link href="/foods.html">See my favorite foods</Link>
        </p>
      </main>
    </div>
  );
}
